[versions]
agp = "8.13.1"
appcompat = "1.7.1"
autoVersion = "1.7.0"
coreKtx = "1.17.0"
credentialsPlayServicesAuth = "1.5.0"
datastorePreferences = "1.2.0"
espressoCore = "3.7.0"
googleid = "1.1.1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
kotlinSerialization = "2.2.21"
kotlinxSerializationCore = "1.9.0"
ksp = "2.2.21-2.0.4"
ktlint = "14.0.1"
okhttp = "5.3.2"
okio = "3.16.4"
playServices = "21.3.0"
testing = "1.0.0"
timber = "5.0.1"
updates = "0.53.0"

[libraries]
androidx-app = { module = "androidx.car.app:app", version.ref = "autoVersion" }
androidx-app-automotive = { module = "androidx.car.app:app-automotive", version.ref = "autoVersion" }
androidx-app-testing = { module = "androidx.car.app:app-testing", version.ref = "autoVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServices" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServices" }
testing = { module = "com.google.assistant.appactions:testing", version.ref = "testing" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
updates = { id = "com.github.ben-manes.versions", version.ref = "updates" }
